USE_CAMERA_STUB := true

#ANDROID_COMMON_BUILD_MK := true

TARGET_NO_RECOVERY := true
TARGET_NO_RADIOIMAGE := true

# inherit from the proprietary version
-include vendor/asus/A66/BoardConfigVendor.mk

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_VARIANT := krait

# Krait optimizations
TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_USE_KRAIT_PLD_SET := true
TARGET_KRAIT_BIONIC_PLDOFFS := 10
TARGET_KRAIT_BIONIC_PLDTHRESH := 10
TARGET_KRAIT_BIONIC_BBTHRESH := 64
TARGET_KRAIT_BIONIC_PLDSIZE := 64
BOARD_USES_QCOM_HARDWARE := true
#BOARD_USES_LEGACY_QCOM := true

TARGET_BOOTLOADER_BOARD_NAME := A66

BOARD_KERNEL_CMDLINE :=  console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 
BOARD_KERNEL_BASE :=  0x80200000
#BOARD_FORCE_RAMDISK_ADDRESS := 0x82200000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_SECOND_OFFSET := 0x00F00000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_SECOND_SIZE := 0
BOADR_DT_SIZE := 0

BOARD_EGL_CFG := device/asus/A66/egl.cfg
TARGET_QCOM_DISPLAY_VARIANT := legacy

#BOARD_USES_HGL := true
#BOARD_USES_OVERLAY := true
USE_OPENGL_RENDERER := true
#BOARD_EGL_NEEDS_LEGACY_FB := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 0xa00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0xa00000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x40000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x6d23f9e00
BOARD_FLASH_BLOCK_SIZE := 131072

#TARGET_PREBUILT_KERNEL := device/asus/A66/kernel
TARGET_KERNEL_SOURCE := kernel/asus/A66
TARGET_KERNEL_CONFIG := A66_defconfig

BOARD_HAS_NO_SELECT_BUTTON := true

#Custom Recovery UI

BOARD_HAS_NO_SELECT_BUTTON := true

#BOARD_USES_GENERIC_AUDIO := false

#BOARD_HAVE_BLUETOOTH := true
#BOARD_HAVE_GPS := true

# Support for dock battery
TARGET_HAS_DOCK_BATTERY := true

# TARGET_RECOVERY_INITRC := device/asus/A66/ramdisk/init.rc
