# Partitions informations
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1610612736
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_USERDATAIMAGE_PARTITION_SIZE := 28760317440
BOARD_PERSISTIMAGE_PARTITION_SIZE := 8388608

# Partitions types
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Partitions blocks
BOARD_FLASH_BLOCK_SIZE := 131072

# Root extra symlinks
BOARD_ROOT_EXTRA_FOLDERS := firmware persist fsg asusdata
BOARD_ROOT_EXTRA_SYMLINKS := /data/tombstones:/tombstones
DONT_DEXPREOPT_PREBUILTS := true
WITH_DEXPREOPT := false

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
