# Audio configurations
AUDIO_FEATURE_ENABLED_COMPRESS_VOIP := true
AUDIO_FEATURE_ENABLED_FLUENCE := true
AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true
AUDIO_FEATURE_ENABLED_PROXY_DEVICE := true
BOARD_USES_ALSA_AUDIO:= true
BOARD_USES_LEGACY_ALSA_AUDIO:= false
BOARD_USES_FLUENCE_INCALL := true
BOARD_USES_SEPERATED_AUDIO_INPUT := true
ifneq ($(BOARD_AOSP_BASED),)
USE_CUSTOM_AUDIO_POLICY := 0
else
USE_CUSTOM_AUDIO_POLICY := 1
endif
USE_XML_AUDIO_POLICY_CONF := 1
