# UI
TARGET_DISABLE_POSTRENDER_CLEANUP := true
TARGET_BOOTANIMATION_HALF_RES := true

# Gralloc
TARGET_ADDITIONAL_GRALLOC_10_USAGE_BITS := 0x2000U | 0x02000000U

# Graphics
HAVE_ADRENO_SOURCE := false
TARGET_CUSTOM_DISPLAY_TUNING := true
TARGET_DISABLE_POSTRENDER_CLEANUP := true
TARGET_USES_POST_PROCESSING := true
USE_MINIKIN := true
